name: Tests

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install pytest pytest-cov

      - name: Run Tests
        run: |
          python -m pytest --cov badges --cov-append tests/ -m "add"
          python -m pytest --cov badges --cov-append tests/ -m "subtract"

      - name: Create Coverage Report
        run: |
          coverage xml --include="badges/*" -o coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

